server:
  port: 8080

spring:
  application:
    name: pet-foster-hub-backend
  profiles:
    active: dev
  
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/pet_foster_hub?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # HikariCP连接池配置
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      connection-timeout: 30000
      pool-name: PetFosterHubHikariPool
  
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
    context-path: /api
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: none  # 禁用自动DDL更新，防止表结构被意外修改
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  
# JWT配置
jwt:
  secret: petFosterHubSecretKey2024ForJWTTokenGeneration
  expiration: 86400000 # 24小时
  refresh-expiration: 604800000 # 7天

# 文件存储配置
file:
  upload:
    path: ./uploads/
    max-size: 10MB

# 日志配置
logging:
  level:
    com.petfosterhub: debug
    org.springframework.security: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ./logs/pet-foster-hub.log

# 开发环境配置
---
spring:
  config:
    activate:
      on-profile: dev
logging:
  file:
    # 开发环境不输出日志到文件
    name: ""

# SpringDoc OpenAPI配置
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  info:
    title: PetFosterHub API
    description: Pet Foster Hub Backend API Documentation
    version: 1.0.0
    contact:
      name: PetFosterHub Team
      email: support@petfosterhub.com

# 短信服务配置
sms:
  api:
    regionId: cn-hangzhou
    secretId: your_access_key_id
    secretKey: your_access_key_secret
  app:
    key: your_app_key  # 应用类型标识，从阿里云控制台获取
  # 频率限制配置
  rate-limit:
    send-sms:
      max-attempts: 50      # 单实例发送限制
      time-window: 1        # 1秒时间窗口
    template-operation:
      max-attempts: 1       # 模板操作限制
      time-window: 1        # 1秒时间窗口